[[kernelarch]]
name = 'arm'
  [[kernelarch.debianarch]]
  name = 'armhf'

[[kernelarch]]
name = 'arm64'
  [[kernelarch.debianarch]]
  name = 'arm64'

[[featureset]]
name = 'rpi'
enable = true
  [featureset.description]
  parts = ['rpi']
  [featureset.description.long]
  rpi = 'This kernel includes the patches for Raspberry Pi platforms.'
  [featureset.description.short]
  rpi = 'Raspberry Pi'

[[debianrelease]]
name_regex = 'UNRELEASED'
abi_version_full = false
abi_suffix = '+unreleased'

[[debianrelease]]
name_regex = 'experimental'
abi_version_full = false
revision_regex = '\d+~exp\d+'

[[debianrelease]]
name_regex = 'unstable'
abi_suffix = '+deb14'
revision_regex = '\d+(\.\d+)?'

[[debianrelease]]
name_regex = 'forky(-security)?'
abi_suffix = '+deb14'
revision_regex = '\d+(\.\d+)?(\+deb14u\d+)?'

[[debianrelease]]
name_regex = 'trixie-backports'
abi_suffix = '+deb13'
revision_regex = '\d+(\.\d+)?(\+deb14u\d+)?~bpo13\+\d+'

[[debianrelease]]
name_regex = 'trixie(-security)?'
abi_suffix = '+rpt'

[[debianrelease]]
name_regex = 'bookworm-backports'
abi_suffix = '+deb12'
revision_regex = '\d+(\.\d+)?(\+deb13u\d+)?~bpo12\+\d+'

# Use default rules for any suite with no explicit config
[[debianrelease]]
name_regex = '.*'

[build]
c_compiler = 'gcc-14'
rust_build_depends = [
  'rustc:native (>= 1.78.0)',
  'bindgen:native (>= 0.65.1)',
  'rust-src (>= 1.78.0)',
]

[relations.image]
depends = [
  'dracut | initramfs-tools (>= 0.120+deb8u2) | linux-initramfs-tool',
]
recommends = [
  'apparmor',
]
breaks = [
  'fwupdate (<< 12-7)',
  'wireless-regdb (<< 2019.06.03-1~)',
]
