[[kernelarch]]
name = 'arm'
  [[kernelarch.debianarch]]
  name = 'armhf'

[[kernelarch]]
name = 'arm64'
  [[kernelarch.debianarch]]
  name = 'arm64'

[[featureset]]
name = 'rpi'
enable = true
  [featureset.description]
  parts = ['rpi']
  [featureset.description.long]
  rpi = 'This kernel includes the patches for Raspberry Pi platforms.'
  [featureset.description.short]
  rpi = 'Raspberry Pi'

[build]
compiler = 'gcc-12'

[relations.image]
depends = [
  'initramfs-tools (>= 0.120+deb8u2) | linux-initramfs-tool',
]
recommends = [
  'apparmor',
]
breaks = [
  'fwupdate (<< 12-7)',
  'wireless-regdb (<< 2019.06.03-1~)',
]
