[[flavour]]
name = "armmp"
[flavour.defs]
is_default = true
[flavour.description]
hardware = 'ARMv7 multiplatform compatible SoCs'
hardware_long = 'ARMv7 multiplatform kernel. See https://wiki.debian.org/DebianKernel/ARMMP for details of supported platforms'
[flavour.packages]
installer = true

[[flavour]]
name = "armmp-lpae"
[flavour.description]
hardware = 'ARMv7 multiplatform compatible SoCs supporting LPAE'
hardware_long = 'ARMv7 multiplatform kernel supporting LPAE. See https://wiki.debian.org/DebianKernel/ARMMP for details of supported platforms.'

[[flavour]]
name = "v6"
[flavour.description]
hardware = 'Raspberry Pi v6'
hardware_long = 'Raspberry Pi v6 kernel'

[[flavour]]
name = "v7"
[flavour.description]
hardware = 'Raspberry Pi v7'
hardware_long = 'Raspberry Pi v7 kernel'

[[featureset]]
name = 'rpi'
[[featureset.flavour]]
name = 'v6'
[[featureset.flavour]]
name = 'v7'

[build]
enable_vdso = true
kernel_file = 'arch/arm/boot/zImage'
kernel_stem = 'vmlinuz'
